version: "3.8"

services:
  webapp_container:
    image: node:20
    container_name: webapp_container
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: >
      sh -c "npm install && npm run build && npm run preview --host"
    ports:
      - "8081:4173"
